### ISSUE TITLE
Docker image for CLI never returns a value

### ISSUE THREAD

**Issue by garrettgalow** [turbobytes/cdnfinder#3]
Following cmd for any site: 
`docker run -it turbobytes/cdnfinder cdnfindercli --phantomjsbin="/bin/phantomjs" --full http://www.cdnplanet.com/ `

always returns:

`{
  "basecdn": null,
  "assetcdn": null,
  "everything": []
 }`

On OSX 10.12.5, with Docker version 17.06.0-ce, build 02c1d87 and latest docker image

**Comment by sajal** [comment]
I can confirm the issue on my end also.

It seems to work when using other URLs. 

    docker run -it turbobytes/cdnfinder cdnfindercli --phantomjsbin="/bin/phantomjs" --full http://www.turbobytes.com/

I will turn on verbose debugging and look into this later.

**Comment by garrettgalow** [comment]
You are write, the 2-3 sites I tested just all happened to fail. It doesn't seem like basecdn or assetcdn ever has a value though - or I have yet to see one.
