### ISSUE TITLE
CDNFinder seems to crash when testing http://www.bbc.co.uk

### ISSUE THREAD

**Issue by aannoune** [turbobytes/cdnfinder#4]
Hello,
 i''ve tried this URL with both  the docker file and you web site and i've got no result.
the docker gives this output: 
````
Error: Failed cdnfinder2018/03/22 07:56:18 /bin/phantomjs is already installed
2018/03/22 07:56:19 Phantomjs had an error

    at /opt/iplabel/tools/CdnFinder/cdn.js:98:31
    at ChildProcess.exithandler (child_process.js:205:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
````

**Comment by sajal** [comment]
I can reproduce the issue. But have not nailed it down.

**http**://www.bbc.co.uk redirects to **https**://www.bbc.co.uk server side, which phantomjs handles well. But then using javascript it navigates to **https**://www.bbc.com/ which redirects to **http**://www.bbc.com (server side)

phantomjs fails soon after it attempts to load **https**://www.bbc.com/

**Comment by aaronpeters** [comment]
Ok. No more time for this

**Comment by sajal** [comment]
ok. Sounds related to ariya/phantomjs#12750
I have adapted workaround from https://github.com/ariya/phantomjs/issues/10389#issuecomment-103650123 which solves the issue. Will be deploying a fix soon.

**Comment by sajal** [comment]
https://www.cdnplanet.com/tools/cdnfinder/#site:http://www.bbc.co.uk/
